# =============================================
#   utils/exporter.py
#   Export generated content to .txt and .docx
# =============================================

import io
from datetime import datetime


def export_to_txt(content_type, topic, tone, platform, content) -> str:
    """Return a formatted plain-text string for download."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""MARKETING CONTENT GENERATOR
{'='*50}
Generated : {timestamp}
Type      : {content_type}
Topic     : {topic}
Tone      : {tone}
Platform  : {platform}
{'='*50}

{content}

{'='*50}
Generated by Marketing Content Generator | Powered by Groq AI
"""


def export_to_docx(content_type, topic, tone, platform, content) -> bytes:
    """Return .docx file as bytes for download."""
    try:
        from docx import Document
        from docx.shared import Pt
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Title
        title = doc.add_heading("Marketing Content Generator", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Metadata table
        doc.add_paragraph()
        table = doc.add_table(rows=4, cols=2)
        table.style = "Table Grid"
        cells = [
            ("Content Type", content_type),
            ("Topic",        topic),
            ("Brand Tone",   tone),
            ("Platform",     platform),
        ]
        for i, (label, value) in enumerate(cells):
            row = table.rows[i]
            row.cells[0].text = label
            row.cells[1].text = value
            row.cells[0].paragraphs[0].runs[0].bold = True

        doc.add_paragraph()
        doc.add_heading("Generated Content", level=1)
        doc.add_paragraph()

        # Content — preserve line breaks and bold headings
        for line in content.split("\n"):
            if line.strip().startswith("**") and line.strip().endswith("**"):
                p   = doc.add_paragraph()
                run = p.add_run(line.strip().replace("**", ""))
                run.bold = True
            else:
                doc.add_paragraph(line)

        doc.add_paragraph()
        footer = doc.add_paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Powered by Groq AI"
        )
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

        buf = io.BytesIO()
        doc.save(buf)
        buf.seek(0)
        return buf.read()

    except ImportError:
        # Fallback to txt if python-docx not available
        return export_to_txt(content_type, topic, tone, platform, content).encode("utf-8")